"""empty message

Revision ID: 23c58fafffae
Revises: 4bb7ba59903c
Create Date: 2022-12-06 21:53:51.507101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23c58fafffae'
down_revision = '4bb7ba59903c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_pic', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profile_pic')
    # ### end Alembic commands ###
